trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: 'quote-winloss-portal-bundle.zip'
    replaceExistingArchive: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'quote-winloss-portal-bundle.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'eci-app-service'
    publishLocation: 'Container'
